spring:
  application:
    name: websearch
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          max-tokens: 500
          tool-names: web_search
server:
  port: 10002
